# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  workpath: 'SportsBetsServer/SportsBetsServer.csproj'
  testpath: 'SportsBetsAPI.Tests/SportsBetsAPI.Tests.csproj'

steps:
- script: dotnet build --configuration $(buildConfiguration) $(workpath)
  displayName: 'dotnet build $(buildConfiguration) $(workpath)'
- script: dotnet test $(testpath) --logger trx
  displayName: 'dotnet test $(testpath)'
